name: fsipy

channels:
  - conda-forge

dependencies:
  - vtk=*=qt*
  - fenics
  - morphman
  - paramiko
  - vmtk
  - pip
  - python >=3.8
  - git
  - pip:
      - git+https://github.com/KVSlab/VaMPy.git
      - git+https://github.com/KVSlab/turtleFSI.git
